sudo: required

install: make get-deps

services:
- docker

before_install:
- make download
- make build

script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- make push